"""Migration 8

Revision ID: 0be6e47b4ad3
Revises: 7c92b623fe8f
Create Date: 2024-06-30 16:22:34.711548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be6e47b4ad3'
down_revision = '7c92b623fe8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.execute(f"UPDATE decks SET forgot_multiplier = 0")
        batch_op.execute(f"UPDATE decks SET hard_multiplier = 1.2")
        batch_op.execute(f"UPDATE decks SET okay_multiplier = 2.5")
        batch_op.execute(f"UPDATE decks SET easy_multiplier = 3.25")

        batch_op.alter_column('forgot_multiplier',
               existing_type=sa.Float(),
               nullable=False)
        batch_op.alter_column('hard_multiplier',
               existing_type=sa.Float(),
               nullable=False)
        batch_op.alter_column('okay_multiplier',
               existing_type=sa.Float(),
               nullable=False)
        batch_op.alter_column('easy_multiplier',
               existing_type=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.alter_column('easy_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('okay_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('hard_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('forgot_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
