"""migration_13

Revision ID: 1ceffdd3ddee
Revises: ddf961114b16
Create Date: 2024-07-23 01:05:50.812609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ceffdd3ddee'
down_revision = 'ddf961114b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_target', sa.INTEGER(), nullable=True))
        
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.execute(f"UPDATE users SET daily_target = 50")
        batch_op.alter_column('daily_target',nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_target')

    # ### end Alembic commands ###
