"""Migration 9

Revision ID: 20d5b475c832
Revises: 0be6e47b4ad3
Create Date: 2024-07-04 23:01:12.839272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d5b475c832'
down_revision = '0be6e47b4ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_remembered_consecutive', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('times_forgot', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('times_forgot')
        batch_op.drop_column('times_remembered_consecutive')

    # ### end Alembic commands ###
