"""Migration 2

Revision ID: 23966a6e1854
Revises: b6b7920ca22b
Create Date: 2024-06-12 12:25:47.075658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23966a6e1854'
down_revision = 'b6b7920ca22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('deck_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_constraint('decks_card_id_fkey', type_='foreignkey')
        batch_op.drop_column('card_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('decks_card_id_fkey', 'cards', ['card_id'], ['id'])

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('deck_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
