"""Migration 10

Revision ID: 3ceaeade1246
Revises: 20d5b475c832
Create Date: 2024-07-04 23:03:01.868554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ceaeade1246'
down_revision = '20d5b475c832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.execute(f"UPDATE cards SET times_remembered_consecutive = 0")
        batch_op.execute(f"UPDATE cards SET times_forgot = 0")

        batch_op.alter_column('times_remembered_consecutive',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('times_forgot',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('times_forgot',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('times_remembered_consecutive',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
