"""Migration 7

Revision ID: 7c92b623fe8f
Revises: f9bb78c6a46f
Create Date: 2024-06-30 16:21:44.546316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c92b623fe8f'
down_revision = 'f9bb78c6a46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('hard_multiplier')
        batch_op.drop_column('okay_multiplier')
        batch_op.drop_column('easy_multiplier')
        batch_op.drop_column('forgot_multiplier')

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forgot_multiplier', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hard_multiplier', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('okay_multiplier', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('easy_multiplier', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('easy_multiplier')
        batch_op.drop_column('okay_multiplier')
        batch_op.drop_column('hard_multiplier')
        batch_op.drop_column('forgot_multiplier')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forgot_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('easy_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('okay_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hard_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
