"""migration_14

Revision ID: 7efe7d697d0e
Revises: 1ceffdd3ddee
Create Date: 2024-07-29 00:21:49.766274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efe7d697d0e'
down_revision = '1ceffdd3ddee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignore_review_time', sa.Boolean(), nullable=True))
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.execute(f"UPDATE decks SET ignore_review_time = FALSE")
        batch_op.alter_column('ignore_review_time',nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('ignore_review_time')

    # ### end Alembic commands ###
