"""Migration 3

Revision ID: cecabe5a7d0c
Revises: 23966a6e1854
Create Date: 2024-06-20 10:58:11.104732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecabe5a7d0c'
down_revision = '23966a6e1854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_for_review', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_interval', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('last_reviewed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviews_done', sa.Integer(), nullable=True))
        batch_op.alter_column('deck_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_reviewed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviews_done', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('reviews_done')
        batch_op.drop_column('last_modified')
        batch_op.drop_column('last_reviewed')
        batch_op.drop_column('time_created')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('deck_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('reviews_done')
        batch_op.drop_column('last_modified')
        batch_op.drop_column('last_reviewed')
        batch_op.drop_column('time_interval')
        batch_op.drop_column('time_for_review')
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###
