"""Migration 12

Revision ID: ddf961114b16
Revises: 5471cfe4d32a
Create Date: 2024-07-08 14:59:23.622480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf961114b16'
down_revision = '5471cfe4d32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('steps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.execute(f"UPDATE cards SET steps = 0")
        batch_op.alter_column('new',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.execute(f"UPDATE cards SET new = True")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('steps',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('new',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
