"""Migration 6

Revision ID: f9bb78c6a46f
Revises: d0a32bd5fd29
Create Date: 2024-06-29 22:46:06.460319

"""
from alembic import op
import sqlalchemy as sa
from datetime import timedelta


# revision identifiers, used by Alembic.
revision = 'f9bb78c6a46f'
down_revision = 'd0a32bd5fd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.execute(f"UPDATE cards SET forgot_multiplier = 0")
        batch_op.execute(f"UPDATE cards SET hard_multiplier = 1.2")
        batch_op.execute(f"UPDATE cards SET okay_multiplier = 2.5")
        batch_op.execute(f"UPDATE cards SET easy_multiplier = 3.25")
       #  batch_op.execute(f"UPDATE cards SET time_interval = {timedelta(seconds=60)}")

        batch_op.alter_column('forgot_multiplier',
               existing_type=sa.Float(),
               nullable=False)
        batch_op.alter_column('hard_multiplier',
               existing_type=sa.Float(),
               nullable=False)
        batch_op.alter_column('okay_multiplier',
               existing_type=sa.Float(),
               nullable=False)
        batch_op.alter_column('easy_multiplier',
               existing_type=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('easy_multiplier',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('okay_multiplier',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hard_multiplier',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('forgot_multiplier',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
